In [1]:
import tensorflow as tf
import numpy as np

In [2]:
rand_a= np.random.uniform(low=10, high=25, size=(5,5))
rand_a

array([[13.50112288, 21.9512615 , 15.07824387, 17.5739252 , 12.64937571],
       [19.54522274, 24.18182865, 16.80143629, 21.49488774, 10.84917539],
       [11.39006586, 12.54395938, 13.71069482, 11.49904066, 11.63276173],
       [24.95642074, 14.26769344, 11.92684659, 19.79060229, 24.44950903],
       [13.07981308, 21.20546286, 23.94612991, 12.06712276, 17.25406607]])

In [3]:
rnd_b = np.random.uniform(low=5, high=10, size=(5,1))
rnd_b

array([[6.59660521],
       [9.12873688],
       [8.51620592],
       [7.30887697],
       [6.01334365]])

In [5]:
a = tf.placeholder(dtype=tf.float32, )
b = tf.placeholder(dtype=tf.float32, )

add = a+b
mul = a*b

In [7]:
with tf.Session() as sess:
    result_add = sess.run(add, feed_dict={a:rand_a, b:rnd_b})   ### single preceptron for adding two input
    print(result_add)
    print()
    result_mul = sess.run(mul, feed_dict={a:rand_a, b:rnd_b})    
    print(result_mul)

[[20.097729 28.547867 21.67485  24.17053  19.245981]
 [28.67396  33.310566 25.930172 30.623625 19.977913]
 [19.906273 21.060165 22.226902 20.015247 20.148968]
 [32.265297 21.57657  19.235723 27.09948  31.758385]
 [19.093157 27.218807 29.959475 18.080467 23.26741 ]]

[[ 89.06158  144.8038    99.465225 115.928246  83.44294 ]
 [178.42319  220.74954  153.37587  196.22118   99.03926 ]
 [ 97.000145 106.82694  116.7631    97.9282    99.06699 ]
 [182.40341  104.280815  87.17185  144.64708  178.69846 ]
 [ 78.65341  127.51574  143.99632   72.56376  103.75463 ]]


## y = mx+c 

In [9]:
x = tf.random_normal(shape=(5,3), mean=1, stddev=1, dtype=tf.float32)
x

<tf.Tensor 'random_normal_1:0' shape=(5, 3) dtype=float32>

In [17]:
m  = tf.random_uniform(shape=(5,1), dtype=tf.float32)
m

<tf.Tensor 'random_uniform_3:0' shape=(5, 1) dtype=float32>

In [22]:
c = tf.random_uniform(shape=(5,1), dtype=tf.float32)
c

<tf.Tensor 'random_uniform_5:0' shape=(5, 1) dtype=float32>

In [32]:
# x = np.random.normal(loc=1, scale=1, size=(5,3))
# m = np.random.uniform(low=5, high=10, size=(5,1))
# c = np.random.uniform(low=5, high=10, size=(5,1))
# print(x, '\n\n', m, '\n\n', c )

[[ 1.67042263  1.50071385 -0.35194172]
 [ 0.5114101   0.3507018   0.95280711]
 [-0.18219647  2.49352553  0.24459305]
 [-1.23910764  2.26091868  0.41980797]
 [ 1.35732253  1.45536585  0.61241434]] 

 [[9.97739708]
 [5.24982549]
 [9.45652508]
 [9.41274633]
 [9.68774558]] 

 [[9.04843104]
 [8.00361663]
 [6.89652244]
 [5.76701251]
 [7.37664773]]


In [33]:
## create placeholder
X = tf.placeholder(dtype=tf.float32)
M = tf.placeholder(dtype=tf.float32)
C = tf.placeholder(dtype=tf.float32)

Y = M * X + C

In [34]:
with tf.Session() as sess:
    y_Cal = sess.run(Y, feed_dict={M:m, X:x, C:c})
    print(y_Cal)

[[25.714901  24.021648   5.536969 ]
 [10.688431   9.84474   13.005688 ]
 [ 5.1735773 30.476608   9.209522 ]
 [-5.896393  27.048466   9.718558 ]
 [20.526043  21.475864  13.309563 ]]


## Single layer Neural Network

In [41]:
Number_Of_Features = 10
Number_Of_Dense_Neuron = 3

In [39]:
# make a tensor placeholder for Training Data

In [42]:
x = tf.placeholder(dtype=tf.float32, shape=(None,Number_Of_Features))

In [43]:
### create two tensor variable for holding Weight and Bias

In [53]:
b = tf.Variable(initial_value = np.ones(shape=(Number_Of_Dense_Neuron)), dtype=tf.float32)
b

<tf.Variable 'Variable_6:0' shape=(3,) dtype=float32_ref>

In [51]:
w = tf.Variable(initial_value = np.random.normal(size=(Number_Of_Features,Number_Of_Dense_Neuron)),dtype=tf.float32)
w

<tf.Variable 'Variable_5:0' shape=(10, 3) dtype=float32_ref>

In [52]:
wx = tf.matmul(x,w)
wx

<tf.Tensor 'MatMul_1:0' shape=(?, 3) dtype=float32>

In [54]:
## As we know Linear Equation y =wx+b

In [56]:
y = wx + b
y

<tf.Tensor 'add_8:0' shape=(?, 3) dtype=float32>

In [57]:
## Add Activation function

In [58]:
activation_function = tf.sigmoid(y)

In [ ]:
x = np.random.normal()

In [60]:
## initialize the variable
init = tf.global_variables_initializer()

In [61]:
with tf.Session() as sess:
    sess.run(init)
    result = sess.run(activation_function, feed_dict={x:np.random.randint(low=1, high=5, size=(1,Number_Of_Features))})

In [62]:
print(result)

[[0.03052617 0.907252   0.99996686]]
