In [20]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.15.0'

### Create a tensorflow constant 

if we print tf.constant directly it will gives us a tensor with datatype and count no.(How many times we have run that particular Constant). AS Follows

In [5]:
string = tf.constant("hello World")
string

<tf.Tensor 'Const_2:0' shape=() dtype=string>

In [13]:
name = tf.constant(" I love Artificial Intelligence")
name

<tf.Tensor 'Const_6:0' shape=() dtype=string>

### Print the tensor value 
we have to create the Session to run this 

In [14]:
with tf.Session() as sess:
    result = sess.run(string + name)
    print(result)

b'hello World I love Artificial Intelligence'


## More practice with Constant

In [15]:
a = tf.constant(10)
b = tf.constant(20)

In [16]:
with tf.Session() as sess:
    result = sess.run(a+b)
    print(result)

30


In [18]:
sum = a+b
sum

<tf.Tensor 'add_11:0' shape=() dtype=int32>

In [19]:
with tf.Session() as sess:
    print(sess.run(sum))

30


#### add Matrix 

In [21]:
mat1 = tf.constant(np.arange(1, 10, 2))
mat1

<tf.Tensor 'Const_9:0' shape=(5,) dtype=int32>

In [22]:
mat2 = tf.constant(np.arange(1,10,2))
mat2

<tf.Tensor 'Const_10:0' shape=(5,) dtype=int32>

In [24]:
add_mat = mat1+mat2
add_mat

<tf.Tensor 'add_13:0' shape=(5,) dtype=int32>

In [25]:
with tf.Session() as sess:
    print(sess.run(add_mat))

[ 2  6 10 14 18]


#### multiplication of element of matrix

In [26]:
mul_mat = mat1*mat2

In [27]:
sess = tf.InteractiveSession()

In [28]:
sess.run(mul_mat)

array([ 1,  9, 25, 49, 81])

### more function

In [30]:
fill_mat = tf.fill(dims=(6,6), value=7)
fill_mat

<tf.Tensor 'Fill_1:0' shape=(6, 6) dtype=int32>

In [31]:
zero_mat = tf.zeros(shape=(3,3))
zero_mat

<tf.Tensor 'zeros:0' shape=(3, 3) dtype=float32>

In [32]:
ones_mat = tf.ones(shape=(3,3))
ones_mat

<tf.Tensor 'ones:0' shape=(3, 3) dtype=float32>

In [33]:
normal_mat = tf.random_normal(shape=(5,4), mean=0.0, stddev=0.5, )
normal_mat

<tf.Tensor 'random_normal:0' shape=(5, 4) dtype=float32>

In [34]:
uniform_mat = tf.random_uniform(shape=(5,5), minval=10, maxval=20, )
uniform_mat

<tf.Tensor 'random_uniform:0' shape=(5, 5) dtype=float32>

In [35]:
matrixx = [fill_mat, zero_mat, ones_mat, normal_mat, uniform_mat]

In [37]:
for i in matrixx:
    print(sess.run(i))
    print('\n')

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[ 0.40301043 -0.05899911  0.28337467  0.1382518 ]
 [ 0.15290385  0.44733563 -0.02961859 -0.17499384]
 [-0.03235369  0.13386522  0.5392727   0.04791074]
 [-0.0665211  -0.09609812 -1.2089839  -0.078175  ]
 [ 0.26908782  0.01407904  1.0108821   0.15573709]]


[[12.489533 16.148302 19.910107 12.797608 14.006092]
 [15.787281 18.878494 13.806085 14.999562 10.902134]
 [15.837922 15.550918 12.350168 12.222506 16.677265]
 [19.846212 15.611132 15.024142 19.273935 17.512688]
 [10.332127 13.477363 14.655029 14.952309 17.495863]]


